name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hzy_normal_network:
    path: ../
  hzy_normal_widget:
    git:
      url: https://gitee.com/tengteng_fan/hzy_normal_widget.git
      ref: master
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.6
  # lottie动画
  lottie: ^1.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
